# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d7a72ff31e1909c01122487795eb0b68"
name = "Pixeo Design"
application_url = "https://pixeo-app-7h8e.onrender.com"
embedded = true

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
uri = "https://pixeo-app-7h8e.onrender.com/webhooks/privacy"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_themes,write_products,write_themes,write_files,read_files,write_metaobjects,read_metaobjects,write_locations,read_locations,write_markets_home,read_markets_home,write_theme_code"

[auth]
redirect_urls = [
  "https://pixeo-app-7h8e.onrender.com/auth/callback",
  "https://pixeo-app-7h8e.onrender.com/auth/shopify/callback",
  "https://pixeo-app-7h8e.onrender.com/api/auth/callback"
]
